CREATE DATABASE movimin;
GO

USE movimin;
GO

CREATE TABLE DatosMovimientos
(
    [Fecha] DATETIME,
    [Origen] NVARCHAR(MAX),
    [Destino] NVARCHAR(MAX),
    [Tonelaje] FLOAT,
    [Material] NVARCHAR(MAX),
    [OrigenNormalizado] NVARCHAR(MAX),
    [Origen2(Rajo)] NVARCHAR(MAX),
    [Fase] NVARCHAR(MAX),
    [CuT] FLOAT,
    [CuS] FLOAT,
    [As] FLOAT,
    [MoT] FLOAT,
    [FeT] FLOAT,
    [Au] FLOAT,
    [Ag] FLOAT,
    [DWI] FLOAT,
    [BWI] FLOAT,
    [TPD_AGUA] FLOAT,
    [DENSIDAD] FLOAT,
    [Factor A] FLOAT,
    [Tpht_mp] FLOAT,
    [Rcum_mp] FLOAT,
    [Rmom_mp] FLOAT,
    [arc_piro] FLOAT,
    [arc_kao] FLOAT,
    [arc_mont] FLOAT,
    [arc_musc] FLOAT,
    [Suma_Arcillas] FLOAT,
    [UGM 1] FLOAT,
    [UGM 2] FLOAT,
    [UGM 3] FLOAT,
    [UGM 4] FLOAT,
    [UGM 5] FLOAT,
    [UGM 6] FLOAT,
    [UGM 11] FLOAT,
    [UGM 12] FLOAT,
    [UGM 13] FLOAT,
    [UGM 14] FLOAT,
    [R1] FLOAT,
    [R2] FLOAT,
    [R3] FLOAT,
    [PQ] FLOAT,
    [SW] FLOAT,
    [UGM] FLOAT,
    [BORNITA] FLOAT,
    [CALCOSINA] FLOAT,
    [CALCOPIRITA] FLOAT,
    [COVELINA] FLOAT,
    [ENARGITA] FLOAT,
    [PIRITA] FLOAT,
    [UCS] FLOAT,
    [grlb_gt80] FLOAT,
    [grlb_ocl] FLOAT,
    [p80_m] FLOAT,
    [arc_piro_2] FLOAT,
    [arc_kao_2] FLOAT,
    [arc_mont_2] FLOAT,
    [arc_musc_2] FLOAT,
    [Suma_Arcillas_2] FLOAT,
    [MULT_CuT] FLOAT,
    [MULT_CuS] FLOAT,
    [MULT_As] FLOAT,
    [MULT_MoT] FLOAT,
    [MULT_FeT] FLOAT,
    [MULT_Au] FLOAT,
    [MULT_Ag] FLOAT,
    [MULT_DWI] FLOAT,
    [MULT_BWI] FLOAT,
    [MULT_TPD_AGUA] FLOAT,
    [MULT_DENSIDAD] FLOAT,
    [MULT_Factor A] FLOAT,
    [MULT_Tpht_mp] FLOAT,
    [MULT_Rcum_mp] FLOAT,
    [MULT_Rmom_mp] FLOAT,
    [MULT_arc_piro] FLOAT,
    [MULT_arc_kao] FLOAT,
    [MULT_arc_mont] FLOAT,
    [MULT_arc_musc] FLOAT,
    [MULT_Suma_Arcillas] FLOAT,
    [MULT_UGM 1] FLOAT,
    [MULT_UGM 2] FLOAT,
    [MULT_UGM 3] FLOAT,
    [MULT_UGM 4] FLOAT,
    [MULT_UGM 5] FLOAT,
    [MULT_UGM 6] FLOAT,
    [MULT_UGM 11] FLOAT,
    [MULT_UGM 12] FLOAT,
    [MULT_UGM 13] FLOAT,
    [MULT_UGM 14] FLOAT,
    [MULT_R1] FLOAT,
    [MULT_R2] FLOAT,
    [MULT_R3] FLOAT,
    [MULT_PQ] FLOAT,
    [MULT_SW] FLOAT,
    [MULT_UGM] FLOAT,
    [MULT_BORNITA] FLOAT,
    [MULT_CALCOSINA] FLOAT,
    [MULT_CALCOPIRITA] FLOAT,
    [MULT_COVELINA] FLOAT,
    [MULT_ENARGITA] FLOAT,
    [MULT_PIRITA] FLOAT,
    [MULT_UCS] FLOAT,
    [MULT_grlb_gt80] FLOAT,
    [MULT_grlb_ocl] FLOAT,
    [MULT_p80_m] FLOAT,
    [MULT_arc_piro_2] FLOAT,
    [MULT_arc_kao_2] FLOAT,
    [MULT_arc_mont_2] FLOAT,
    [MULT_arc_musc_2] FLOAT,
    [MULT_Suma_Arcillas_2] FLOAT
);

CREATE TABLE movimin_2
(
    id INT IDENTITY(1,1) PRIMARY KEY,
    [fecha] DATE,
    [ton] DECIMAL(18,6),
    [cut] DECIMAL(18,6),
    [cus] DECIMAL(18,6),
    [ast] DECIMAL(18,6),
    [mot] DECIMAL(18,6),
    [fet] DECIMAL(18,6),
    [au] DECIMAL(18,6),
    [ag] DECIMAL(18,6),
    [dwi] DECIMAL(18,6),
    [bwi] DECIMAL(18,6),
    [ai] DECIMAL(18,6),
    [vsed] DECIMAL(18,6),
    [ph] DECIMAL(18,6),
    [tpd_agua] DECIMAL(18,6),
    [dens] DECIMAL(18,6),
    [factor_a] DECIMAL(18,6),
    [tpha] DECIMAL(18,6),
    [rcum_mp] DECIMAL(18,6),
    [rmom_mp] DECIMAL(18,6),
    [pirofilita] DECIMAL(18,6),
    [kaolinita] DECIMAL(18,6),
    [illita] DECIMAL(18,6),
    [muscovita] DECIMAL(18,6),
    [suma_arcillas] DECIMAL(18,6),
    [suma_arcillas_2] DECIMAL(18,6),
    [ugm2] DECIMAL(18,6),
    [ugm3] DECIMAL(18,6),
    [ugm4] DECIMAL(18,6),
    [ugm5] DECIMAL(18,6),
    [ugm6] DECIMAL(18,6),
    [ugm11] DECIMAL(18,6),
    [ugm12] DECIMAL(18,6),
    [ugm13] DECIMAL(18,6),
    [ugm14] DECIMAL(18,6),
    [r1] DECIMAL(18,6),
    [r2] DECIMAL(18,6),
    [pq] DECIMAL(18,6),
    [r3] DECIMAL(18,6),
    [sw] DECIMAL(18,6),
    [bornita] DECIMAL(18,6),
    [calcosina] DECIMAL(18,6),
    [calcopirita] DECIMAL(18,6),
    [covelina] DECIMAL(18,6),
    [enargita] DECIMAL(18,6),
    [pirita] DECIMAL(18,6),
    [ucs] DECIMAL(18,6),
    [grlb_gt80] DECIMAL(18,6),
    [grlb_ocl] DECIMAL(18,6),
    [p80_m] DECIMAL(18,6),
    [tpo_resid] DECIMAL(18,6),
    [ugf1] DECIMAL(18,6),
    [ugf2] DECIMAL(18,6),
    [ugf3] DECIMAL(18,6),
    [ugf4] DECIMAL(18,6),
    [ugf5] DECIMAL(18,6),
    [rec_glob] DECIMAL(18,6)
);

CREATE TABLE CS01_CS02_CS03
(
    id INT IDENTITY(1,1) PRIMARY KEY,
    [Fecha] DATE,
    [Ton] DECIMAL(18,4),
    [CuT] DECIMAL(18,4),
    [CuS] DECIMAL(18,4),
    [AsT] DECIMAL(18,4),
    [MoT] DECIMAL(18,4),
    [FeT] DECIMAL(18,4),
    [tph] DECIMAL(18,4),
    [rcu] DECIMAL(18,4),
    [rmo] DECIMAL(18,4),
    [Dif] DECIMAL(18,4),
    [Report VPOM] DECIMAL(18,4),
    [Operativo] DECIMAL(18,4),
    [Chancado & Correa] DECIMAL(18,4),
    [tpha] DECIMAL(18,4),
    [rcu.1] DECIMAL(18,4),
    [rmo.1] DECIMAL(18,4),
    [% solid planta] DECIMAL(18,4),
    [M] DECIMAL(18,4),
    [rec limp] DECIMAL(18,4),
    [Restricción L1] DECIMAL(18,4),
    [Restricción L2] DECIMAL(18,4),
    [Restricción L3] DECIMAL(18,4),
    [p80] DECIMAL(18,4),
    [SAG 1] DECIMAL(18,4),
    [SAG 2] DECIMAL(18,4),
    [SAG 1011] DECIMAL(18,4),
    [Línea 1] DECIMAL(18,4),
    [Línea 2] DECIMAL(18,4),
    [Línea 3] DECIMAL(18,4),
    [MB 3] DECIMAL(18,4),
    [MB 4] DECIMAL(18,4),
    [MB 1012] DECIMAL(18,4),
    [MB 1013] DECIMAL(18,4),
    [MB 3.1] DECIMAL(18,4),
    [MB 4.1] DECIMAL(18,4),
    [MB 1012.1] DECIMAL(18,4),
    [MB 1013.1] DECIMAL(18,4)
);

CREATE TABLE Usuarios
(
    id INT IDENTITY(1,1) PRIMARY KEY,
    nombre NVARCHAR(255),
    email NVARCHAR(255),
    estado INT,
    perfil TINYINT,
    CONSTRAINT CHK_Perfil CHECK (perfil IN (1, 2))
);

CREATE TABLE dbo.Auth
(
    id INT IDENTITY(1,1) PRIMARY KEY,
    fk_usuario_id INT,
    password NVARCHAR(MAX),
    salt NVARCHAR(MAX),
    ultimo_login DATETIME,
    intentos_fallidos INT,
    bloqueado BIT,
    token_recuperacion NVARCHAR(MAX),
    fecha_token DATETIME,
    [user] NVARCHAR(255) NOT NULL,
    totp_secret NVARCHAR(MAX),
    totp_enabled BIT,
    CONSTRAINT FK_Auth_Usuarios FOREIGN KEY (fk_usuario_id)
        REFERENCES Usuarios(id)
);









